### ISSUE TITLE
Can't minify with create-react-app

### ISSUE THREAD

**Issue by jordanambra** [rubenspgcavalcante/instascan-umd#1]
Hi, I'm using your react-instascan library, and whenever I run a build it fails with the following error:

```
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/instascan-umd/dist/instascan.js:8:199754 

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

I'm not sure exactly why this is happening, but it doesn't appear to be anything from my build process. Any ideas?

**Comment by rubenspgcavalcante** [comment]
Hmm, I think is related to the minifying level defined inside the webpack when you use create-react-app. It uses an aggressive minification setup that causes this error.

**Comment by jordanambra** [comment]
What's rearca? Is that one of the dependencies you are using? I think what's happening is that it's trying to minify a file that's already minified.

**Comment by rubenspgcavalcante** [comment]
Sorry, I was on the phone and the corrector set "rearca" (create-react-app) 😆 
(Although I changed the ticket title too)
Yes probably the minification method breaks on a already minified file. Maybe for now you can set it to exclude it from minification.
Seems related to https://github.com/facebook/create-react-app/issues/3734
